spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 8080
  servlet:
    session:
      timeout: 120m


logging:
  config: classpath:logback-spring.xml