package com.xinzhi.furniture.mall.db.dao;

import com.xinzhi.furniture.mall.db.domain.LitemallWalletFlow;
import com.xinzhi.furniture.mall.db.domain.LitemallWalletFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallWalletFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    long countByExample(LitemallWalletFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallWalletFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int insert(LitemallWalletFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int insertSelective(LitemallWalletFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    LitemallWalletFlow selectOneByExample(LitemallWalletFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    LitemallWalletFlow selectOneByExampleSelective(@Param("example") LitemallWalletFlowExample example, @Param("selective") LitemallWalletFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    List<LitemallWalletFlow> selectByExampleSelective(@Param("example") LitemallWalletFlowExample example, @Param("selective") LitemallWalletFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    List<LitemallWalletFlow> selectByExample(LitemallWalletFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    LitemallWalletFlow selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallWalletFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    LitemallWalletFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallWalletFlow record, @Param("example") LitemallWalletFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallWalletFlow record, @Param("example") LitemallWalletFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallWalletFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallWalletFlow record);
}