package com.xinzhi.furniture.mall.db.dao;

import com.xinzhi.furniture.mall.db.domain.LitemallWallet;
import com.xinzhi.furniture.mall.db.domain.LitemallWalletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallWalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    long countByExample(LitemallWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int insert(LitemallWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int insertSelective(LitemallWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    LitemallWallet selectOneByExample(LitemallWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    LitemallWallet selectOneByExampleSelective(@Param("example") LitemallWalletExample example, @Param("selective") LitemallWallet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    List<LitemallWallet> selectByExampleSelective(@Param("example") LitemallWalletExample example, @Param("selective") LitemallWallet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    List<LitemallWallet> selectByExample(LitemallWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    LitemallWallet selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallWallet.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    LitemallWallet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallWallet record, @Param("example") LitemallWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallWallet record, @Param("example") LitemallWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallWallet record);
}