package com.xinzhi.furniture.mall.db.dao;

import com.xinzhi.furniture.mall.db.domain.LitemallGoodsOption;
import com.xinzhi.furniture.mall.db.domain.LitemallGoodsOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallGoodsOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    LitemallGoodsOption selectOneByExample(LitemallGoodsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    LitemallGoodsOption selectOneByExampleSelective(@Param("example") LitemallGoodsOptionExample example, @Param("selective") LitemallGoodsOption.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    List<LitemallGoodsOption> selectByExampleSelective(@Param("example") LitemallGoodsOptionExample example, @Param("selective") LitemallGoodsOption.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    List<LitemallGoodsOption> selectByExample(LitemallGoodsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    LitemallGoodsOption selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsOption.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    LitemallGoodsOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsOption record, @Param("example") LitemallGoodsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsOption record, @Param("example") LitemallGoodsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsOption record);
}