package com.xinzhi.furniture.mall.db.dao;

import com.xinzhi.furniture.mall.db.domain.LitemallGoodsOptionTmp;
import com.xinzhi.furniture.mall.db.domain.LitemallGoodsOptionTmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallGoodsOptionTmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsOptionTmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsOptionTmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsOptionTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsOptionTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    LitemallGoodsOptionTmp selectOneByExample(LitemallGoodsOptionTmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    LitemallGoodsOptionTmp selectOneByExampleSelective(@Param("example") LitemallGoodsOptionTmpExample example, @Param("selective") LitemallGoodsOptionTmp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    List<LitemallGoodsOptionTmp> selectByExampleSelective(@Param("example") LitemallGoodsOptionTmpExample example, @Param("selective") LitemallGoodsOptionTmp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    List<LitemallGoodsOptionTmp> selectByExample(LitemallGoodsOptionTmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    LitemallGoodsOptionTmp selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsOptionTmp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    LitemallGoodsOptionTmp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsOptionTmp record, @Param("example") LitemallGoodsOptionTmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsOptionTmp record, @Param("example") LitemallGoodsOptionTmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsOptionTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_option_tmp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsOptionTmp record);
}