package com.xinzhi.furniture.mall.db.dao;

import com.xinzhi.furniture.mall.db.domain.LitemallWalletTopUp;
import com.xinzhi.furniture.mall.db.domain.LitemallWalletTopUpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LitemallWalletTopUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    long countByExample(LitemallWalletTopUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallWalletTopUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int insert(LitemallWalletTopUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int insertSelective(LitemallWalletTopUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    LitemallWalletTopUp selectOneByExample(LitemallWalletTopUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    LitemallWalletTopUp selectOneByExampleSelective(@Param("example") LitemallWalletTopUpExample example, @Param("selective") LitemallWalletTopUp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    List<LitemallWalletTopUp> selectByExampleSelective(@Param("example") LitemallWalletTopUpExample example, @Param("selective") LitemallWalletTopUp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    List<LitemallWalletTopUp> selectByExample(LitemallWalletTopUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    LitemallWalletTopUp selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallWalletTopUp.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    LitemallWalletTopUp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallWalletTopUp record, @Param("example") LitemallWalletTopUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallWalletTopUp record, @Param("example") LitemallWalletTopUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallWalletTopUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_wallet_top_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallWalletTopUp record);
}